# Generated by Django 2.0.7 on 2018-10-29 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChuyenNganhSinhVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chuyen_nganh', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DanhGiaSach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NguoiQuanLyThuVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmnd', models.CharField(max_length=200, unique=True)),
                ('ho_va_ten', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nam', 'Nu')], default='Nam', max_length=3)),
                ('dia_chi_nha', models.CharField(max_length=300)),
                ('ma_so_quan_ly', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhongThuVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_so_phong', models.CharField(max_length=100, unique=True)),
                ('so_luong_sach_toi_da_co_the_chua', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_sach', models.CharField(max_length=100)),
                ('tac_gia', models.CharField(max_length=100)),
                ('nam_xuat_ban', models.IntegerField(default=0)),
                ('gia_ban', models.IntegerField(default=0)),
                ('so_luong_ton_kho', models.IntegerField(default=0)),
                ('so_luong_da_cho_muon', models.IntegerField(default=0)),
                ('so_luong_da_ban', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmnd', models.CharField(max_length=200, unique=True)),
                ('ho_va_ten', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nam', 'Nu')], default='Nam', max_length=3)),
                ('dia_chi_nha', models.CharField(max_length=300)),
                ('ma_so_sinh_vien', models.CharField(max_length=100, unique=True)),
                ('chuyen_nganh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thuvienbk.ChuyenNganhSinhVien')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SinhVienMuaSach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_mua', models.DateTimeField()),
                ('sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thuvienbk.Sach')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thuvienbk.SinhVien')),
            ],
        ),
        migrations.CreateModel(
            name='SinhVienMuonSach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_muon', models.DateTimeField()),
                ('sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thuvienbk.Sach')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thuvienbk.SinhVien')),
            ],
        ),
        migrations.CreateModel(
            name='TheLoaiSach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_loai_sach', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sach',
            name='the_loai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thuvienbk.TheLoaiSach'),
        ),
        migrations.AddField(
            model_name='nguoiquanlythuvien',
            name='phong_thu_vien_quan_ly',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='thuvienbk.PhongThuVien'),
        ),
        migrations.AddField(
            model_name='danhgiasach',
            name='sach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thuvienbk.Sach'),
        ),
        migrations.AddField(
            model_name='danhgiasach',
            name='sinh_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thuvienbk.SinhVien'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thuvienbk.Question'),
        ),
    ]
