# Generated by Django 2.0.7 on 2018-10-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thuvienbk', '0002_auto_20181029_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoiquanlythuvien',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
