# Generated by Django 2.0.7 on 2018-10-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thuvienbk', '0003_auto_20181029_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinhvien',
            name='password',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
