# Generated by Django 2.0.7 on 2018-10-29 06:54

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thuvienbk', '0004_sinhvien_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='nguoiquanlythuvien',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sinhvien',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='nguoiquanlythuvien',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='password',
        ),
        migrations.AddField(
            model_name='nguoiquanlythuvien',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
