# Generated by Django 2.0.7 on 2018-10-29 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thuvienbk', '0005_auto_20181029_0354'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='nguoiquanlythuvien',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='sinhvien',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='nguoiquanlythuvien',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='sinhvien',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='nguoiquanlythuvien',
            name='id',
            field=models.AutoField(auto_created=True,primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nguoiquanlythuvien',
            name='user',
            field=models.OneToOneField( on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='user',
            field=models.OneToOneField( on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
