# Generated by Django 2.1.3 on 2018-11-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thuvienbk', '0006_auto_20181029_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoiquanlythuvien',
            name='gioi_tinh',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nu', 'Nu')], default='Nam', max_length=3),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='gioi_tinh',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nu', 'Nu')], default='Nam', max_length=3),
        ),
    ]
